export const EventsData = [
  {
    id: 1,
    etkinlik_adi: "Dengbej Dinletisi",
    tur: "Müzik",
    katilimci: "Seyithan Koç",
    etkinlik_tarihi: "2024-12-20",
    saat: "13:00",
    mekan: "Diyarbakır Dengbêj Evi",
    adres: "Ziya Gökalp, Kılıçı Sk., 21300 Sur/Diyarbakır",
    iletisim: "(544) 9338918",
    bilet: "yok",
    kapasite: null,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 0,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 0,
    },
    images: "../images/dengbej.jpg",
    aciklama:
      "Diyarbakır Kültüründe ki Dengbejleri yaşatabilmek için Dengbej Dinletimize herkesi bekleriz.",
  },
  {
    id: 2,
    etkinlik_adi: "Kurmanci (Kürtçe) A1 Seviyesi Dersi",
    tur: "Eğitim",
    katilimci: "Renas Kaya",
    etkinlik_tarihi: "2024-12-20",
    saat: "12:00",
    mekan: "Dismek Sümerpark Kurs Merkezi",
    adres:
      "Şehitlik, Büyükşehir Bld. Sümer Park İçi Yolu, 21010 Yenişehir/Diyarbakır",
    iletisim: "(893) 1607659",
    bilet: "yok",
    kapasite: 50,
    "katilim-durumu": "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 0,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 0,
    },
    images: "../images/kurmanci-a1.jpeg",
    aciklama:
      "Çok zengin dil olan Kurmanci (Kürtçe) A1 dersimize herkesi bekleriz.",
  },
  {
    id: 3,
    etkinlik_adi: "Zerzevan Kalesi Gezisi",
    tur: "Gezi",
    katilimci: "Diyarbakır Tarihini Yaşatma Derneği",
    etkinlik_tarihi: "2024-12-20",
    saat: "09:00",
    mekan: "Zerzevan Kalesi",
    iletisim: "(104) 2437094",
    bilet: "http://dummyimage.com/111x100.png/ff4444/ffffff",
    kapasite: 50,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 500,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 250,
    },
    images: "../images/Zerzevan.jpg",
    aciklama:
      "Zerzevan Kalesi, Roma döneminde kalma, Diyarbakır'da yer alan tarihi bir mirastır. Gezimize herkesi bekleriz",
  },
  {
    id: 4,
    etkinlik_adi: "Karacadağ Kayak Aktivitesi",
    tur: "Aktivite",
    katilimci: "Diyarbakır Gençlik Merkezi",
    etkinlik_tarihi: "2024-12-20",
    saat: "11:00",
    mekan: "Karacadağ Kayak Merkezi",
    iletisim: "(405) 5825863",
    bilet: "http://dummyimage.com/108x100.png/ff4444/ffffff",
    kapasite: 75,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 600,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 400,
    },
    images: "../images/Karacadag.jpg",
    aciklama: "Karacadağ Kayak Aktivitesine herkesi bekleriz.",
  },
  {
    id: 6,
    etkinlik_adi: "Diyarbakır El Sanatları Çömlekçilik",
    tur: "Eğitim",
    katilimci: "Emine Güler",
    etkinlik_tarihi: "2024-01-27",
    saat: "12:00",
    mekan: "Sur Halk Eğitim Merkezi",
    adres: "İskenderpaşa, İnönü Cad. Sur Kaymakamlığı, 21300 Sur/Diyarbakır",
    iletisim: "(674) 8258122",
    bilet: "yok",
    kapasite: 50,
    katilim_durumu: "Dolmak Üzere",
    ucret: {
      miktar: 0,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 0,
    },
    images: "../images/El-Sanatlari.jpg",
    aciklama:
      "Diyarbakır El Sanatları'nın Çomlekçilik dersine herkesi bekleriz.",
  },
  {
    id: 7,
    etkinlik_adi: "Zazakî (Zazaca) A1 Seviyesi Dersi",
    tur: "Eğitim",
    katilimci: "Hevidar Arslan",
    etkinlik_tarihi: "2024-03-25",
    saat: "16:00",
    mekan: "Dismek Sümerpark Kurs Merkezi",
    adres:
      "Şehitlik, Büyükşehir Bld. Sümer Park İçi Yolu, 21010 Yenişehir/Diyarbakır",
    iletisim: "(180) 5869634",
    bilet: "yok",
    kapasite: 50,
    katilim_durumu: "Müsait",
    ucret: {
      miktar: 0,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 0,
    },
    images: "../images/Zazaki-a1.webp",
    aciklama: "Zazakî (Zazaca) A1 Seviyesi dersine herkesi bekleriz.",
  },
  {
    id: 8,
    etkinlik_adi: "Mem Ararat Konseri",
    tur: "Konser",
    katilimci: "Mem Ararat",
    etkinlik_tarihi: "2024-04-21",
    saat: "20:00",
    mekan: "Diyarbakır Sezai Karakoç Kültür ve Kongre Merkezi",
    adres: "Yenişehir, Istasyon Cd No:65, 21100 Yenişehir/Diyarbakır",
    iletisim: "(276) 9675107",
    bilet: "http://dummyimage.com/219x100.png/5fa2dd/ffffff",
    kapasite: 500,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 350,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 100,
    },
    images: "../images/Ararat.webp",
    aciklama: "Mem Ararat Konserine  herkesi bekleriz.",
  },
  {
    id: 9,
    etkinlik_adi: "Diyarbakır 8. Kitap Fuarı",
    tur: "Fuar",
    katilimci: "Tüm Diyarbakır Halkı",
    etkinlik_tarihi: "2024-11-30",
    saat: "08:30",
    mekan: "Diyarbakır Fuar Alanı",
    adres: "İş Kuleleri Kule 1 Kat 7 34330 4.",
    iletisim: "(912) 6682016",
    bilet: "yok",
    kapasite: null,
    katilim_durumu: "Dolu",
    ucret: {
      miktar: 0,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 0,
    },
    images: "../images/Kitap-a1.jpg",
    aciklama: "Diyarbakır 8. Kitap Fuarına herkesi bekleriz.",
  },
  {
    id: 10,
    etkinlik_adi: "Yöresel Lezzetler Festivali",
    tur: "Festival",
    katilimci: "Tüm Diyarnakır Halkı",
    etkinlik_tarihi: "2024-01-25",
    saat: "11:00",
    mekan: "Bismil Meydan Park",
    adres: "Altıok, Özgürlük Blv., 21500 Bismil/Diyarbakır",
    iletisim: "(850) 8192626",
    bilet: "yok",
    kapasite: null,
    "katilim,_durumu": "Dolmak Üzere",
    ucret: {
      miktar: 0,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 0,
    },
    images: "../images/yoresel-lezzet.webp ",
    aciklama: "Yöresel Lezzetler Festivaline herkesi bekleriz.",
  },
  {
    id: 11,
    etkinlik_adi: "Mehmet Atlı Konseri",
    tur: "Konser",
    katilimci: "Mehmet Atlı",
    etkinlik_tarihi: "2024-04-21",
    saat: "19:00",
    mekan: "Diyarbakır Sezai Karakoç Kültür ve Kongre Merkezi",
    adres: "Yenişehir, Istasyon Cd No:65, 21100 Yenişehir/Diyarbakır",
    iletisim: "(276) 9675107",
    bilet: "http://dummyimage.com/229x100.png/5fa2dd/ffffff",
    kapasite: 500,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 0,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 0,
    },
    images: "../images/mehmet-atli.jpg",
    aciklama: "Mehmet Atlı Konserine  herkesi bekleriz.",
  },
  {
    id: 12,
    etkinlik_adi: "Diyarbakır El Sanatları Kalaycılık",
    tur: "Eğitim",
    katilimci: "Abdullah Yılmaz",
    etkinlik_tarihi: "2024-01-27",
    saat: "15:00",
    mekan: "Sur Halk Eğitim Merkezi",
    adres: "İskenderpaşa, İnönü Cad. Sur Kaymakamlığı, 21300 Sur/Diyarbakır",
    iletisim: "(574) 9258922",
    bilet: "yok",
    kapasite: 50,
    katilim_durumu: "Dolu",
    ucret: {
      miktar: 0,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 0,
    },
    images: "../images/Kalaycilik.webp",
    aciklama: "Diyarbakır El Sanatları Kalaycılık Eğitimine herkesi bekleriz.",
  },
  {
    id: 13,
    etkinlik_adi: "Diyarbakır Yöresel Giyim Sergisi",
    tur: "Sergi",
    katilimci: "Berfin Çelik",
    etkinlik_tarihi: "2024-03-06",
    saat: "08:00",
    mekan: "Diyarbakır Sanat Merkezi",
    adres:
      "Kurt İsmail Paşa 2. Sok., Güneş Plaza Kat:6 No:14, 21100 Yenişehir/Diyarbakır",
    iletisim: "(594) 2329666",
    bilet: "yok",
    kapasite: null,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 0,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 0,
    },
    images: "../images/Giyim.webp",
    aciklama: "Diyarbakır Yöresel Giyim Sergisine herkesi bekleriz.",
  },
  {
    id: 14,
    etkinlik_adi: "Tarihin Tozlu Raflarından Diyarbakır Müzesi Gezisi",
    tur: "Gezi",
    katilimci: "Diyarbakır Tarihini Yaşatma Derneği",
    etkinlik_tarihi: "2024-03-14",
    saat: "12:00",
    mekan: "Diyarbakır Arkeoloji Müzesi",
    adres: "Cevat Paşa",
    iletisim: "(884) 2535874",
    bilet: "http://dummyimage.com/108x100.png/ff4444/ffffff",
    kapasite: 75,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 200,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 100,
    },
    images: "../images/Muze.jpg",
    aciklama:
      "Tarihin Tozlu Raflarından Diyarbakır Müzesi Gezisine herkesi bekleriz.",
  },
  {
    id: 15,
    etkinlik_adi: "Kurmanci (Kürtçe) A2 Seviyesi Dersi",
    tur: "Dil Eğitimi",
    katilimci: "Renas Kaya",
    etkinlik_tarihi: "2024-06-16",
    saat: "12:00",
    mekan: "Dismek Sümerpark Kurs Merkezi",
    adres:
      "Şehitlik, Büyükşehir Bld. Sümer Park İçi Yolu, 21010 Yenişehir/Diyarbakır",
    iletisim: "(893) 1607659",
    bilet: "yok",
    kapasite: 50,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 0,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 0,
    },
    images: "../images/Kurmanci-a2.jpeg",
    aciklama: "Kurmanci (Kürtçe) A2 Seviyesi Dersine herkesi bekleriz.",
  },
  {
    id: 16,
    etkinlik_adi: "Diyarbakır Klasik Müzik Festivali",
    tur: "Konser",
    katilimci: "Fazıl Say",
    etkinlik_tarihi: "2024-12-08",
    saat: "19:00",
    mekan: "Diyarbakır Sezai Karakoç Kültür ve Kongre Merkezi",
    adres: "İstasyon Cad. No:65",
    iletisim: "(494) 2439103",
    bilet: "http://dummyimage.com/219x100.png/5fa2dd/ffffff",
    kapasite: 100,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 250,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 150,
    },
    images: "../images/Klasik.webp",
    aciklama: "Diyarbakır Klasik Müzik Festivaline herkesi bekleriz.",
  },
  {
    id: 17,
    etkinlik_adi: "Diyarbakır Surlarında Tarih Turu",
    tur: "Gezi",
    katilimci: "Diyarbakır Rehberler Derneği",
    etkinlik_tarihi: "2024-12-08",
    saat: "13:00",
    mekan: "Diyarbakır Surları",
    adres: "Diyarbakır Sur İçi",
    iletisim: "(532) 7654321",
    bilet: "http://dummyimage.com/108x100.png/ff4444/ffffff",
    kapasite: 100,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 100,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 50,
    },
    images: "../images/Surlarinda.jpg",
    aciklama: "Diyarbakır Surlarında Tarih Turuna herkesi bekleriz.",
  },
  {
    id: 18,
    etkinlik_adi: "On Gözlü Köprü Fotoğraf Çekimi Workshopu",
    tur: "Eğitim",
    katilimci: "Ahmet Şahin",
    etkinlik_tarihi: "2024-12-08",
    saat: "16:00",
    mekan: "On Gözlü Köprü",
    adres: "Mardin Yolu Üzeri, 21000 Sur/Diyarbakır",
    iletisim: "(534) 1234567",
    bilet: "yok",
    kapasite: 100,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 0,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 0,
    },
    images: "../images/on-gozlu.jpg",
    aciklama: "On Gözlü Köprü Fotoğraf Çekimi Workshopuna herkesi bekleriz.",
  },
  {
    id: 19,
    etkinlik_adi: "Diyarbakır Karpuz Festivali",
    katilimci: "Diyarbakır Ziraat Odası",
    tur: "Festival",
    etkinlik_tarihi: "2024-12-08",
    saat: "14:00",
    mekan: "Hevsel Bahçeleri",
    adres: "Hevsel Bahçeleri, 21000 Sur/Diyarbakır",
    iletisim: "(539) 8765432",
    bilet: "yok",
    kapasite: null,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 0,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 0,
    },
    images: "../images/karpuz.png",
    aciklama: "Diyarbakır Karpuz Festivaline herkesi bekleriz.",
  },
  {
    id: 20,
    etkinlik_adi: "Diyarbakır Mutfağı Yemek Atölyesi",
    tur: "Eğitim",
    katilimci: "Zeynep Karakuş",
    etkinlik_tarihi: "2024-06-20",
    saat: "10:00",
    mekan: "Diyarbakır Gastronomi Merkezi",
    adres: "Yenişehir, Bağlar Cd. No:23, 21100 Diyarbakır",
    iletisim: "(545) 9876543",
    bilet: "yok",
    kapasite: null,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 0,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 0,
    },
    images: "../images/Yemek.jpg",
    aciklama: "Diyarbakır Mutfağı Yemek Atölyesine herkesi bekleriz.",
  },
  {
    id: 21,
    etkinlik_adi: "Hasan Paşa Hanı Sanat Sergisi",
    tur: "Sergi",
    katilimci: "Mahsun Tekin",
    etkinlik_tarihi: "2024-12-08",
    saat: "11:00",
    mekan: "Hasan Paşa Hanı",
    adres: "Gazi Cd. No:35, Sur/Diyarbakır",
    iletisim: "(541) 5432198",
    bilet: "yok",
    kapasite: null,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 0,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_ndirimli_miktar: 0,
    },
    images: "../images/Hasan.jpg",
    aciklama: "Hasan Paşa Hanı Sanat Sergisine herkesi bekleriz.",
  },
  {
    id: 22,
    etkinlik_adi: "Zaza Halk Dansları Gösterisi",
    katilimci: "Zaza Kültür Sanat Derneği",
    tur: "Dans",
    etkinlik_tarihi: "2024-12-08",
    saat: "19:00",
    mekan: "Diyarbakır Amfi Tiyatro",
    adres: "Yenişehir, Tiyatro Cd. No:12, 21100 Diyarbakır",
    iletisim: "(537) 4567890",
    bilet: "http://dummyimage.com/108x100.png/ff4444/ffffff",
    kapasite: 300,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 100,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 50,
    },
    images: "../images/Zaza.jpg",
    aciklama: "Zaza Halk Dansları Gösterisine herkesi bekleriz.",
  },
  {
    id: 23,
    etkinlik_adi: "Zazakî (Zazaca) A2 Seviyesi Dersi",
    tur: "Eğitim",
    katilimci: "Hevidar Arslan",
    etkinlik_tarihi: "2024-12-07",
    saat: "16:00",
    mekan: "Dismek Sümerpark Kurs Merkezi",
    adres:
      "Şehitlik, Büyükşehir Bld. Sümer Park İçi Yolu, 21010 Yenişehir/Diyarbakır",
    iletisim: "(180) 5869634",
    bilet: "yok",
    kapasite: 50,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 0,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 0,
    },
    images: "../images/Zazaki-a2.jpeg",
    aciklama: "Zazakî (Zazaca) A2 Seviyesi dersine herkesi bekleriz.",
  },
  {
    id: 24,
    etkinlik_adi: "Hevsel Bahçeleri Doğa Yürüyüşü",
    tur: "Doğa Aktivitesi",
    katilimci: "Diyarbakır Doğa Kulübü",
    etkinlik_tarihi: "2024-12-08",
    saat: "08:00",
    mekan: "Hevsel Bahçeleri",
    adres: "Hevsel Bahçeleri, 21000 Sur/Diyarbakır",
    iletisim: "(532) 9988776",
    bilet: "yok",
    kapasite: 100,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 0,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 0,
    },
    images: "../images/hevsel.jpeg",
    aciklama: "Hevsel Bahçeleri Doğa Yürüyüşüne herkesi bekleriz.",
  },
  {
    id: 25,
    etkinlik_adi: "Diyarbakır Çocuk Oyunları Festivali",
    tur: "Festival",
    katilimci: "Tüm Diyarnakır Halkı",
    etkinlik_tarihi: "2024-12-08",
    saat: "10:00",
    mekan: "Diyarbakır Büyükşehir Belediyesi Meydanı",
    adres: "Yenişehir, İstasyon Cd. No:12, Diyarbakır",
    iletisim: "(534) 6655443",
    bilet: "yok",
    kapasite: null,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 0,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 0,
    },
    images: "../images/cocuk.jpg",
    aciklama: "Diyarbakır Çocuk Oyunları Festivaline herkesi bekleriz.",
  },
  {
    id: 26,
    etkinlik_adi: "Kültürel El Sanatları Workshopu",
    tur: "Eğitim",
    katilimci: "Elif Kaya",
    etkinlik_tarihi: "2024-12-07",
    saat: "14:00",
    mekan: "Sur Halk Eğitim Merkezi",
    adres: "İskenderpaşa, İnönü Cad. No:15, 21300 Sur/Diyarbakır",
    iletisim: "(541) 2233445",
    bilet: "yok",
    kapasite: null,
    katilim_durumu: "Müsait/Dolmak Üzere/Dolu",
    ucret: {
      miktar: 0,
      para_birimi: "TL",
      ogrenci_indirimi: true,
      ogrenci_indirimli_miktar: 0,
    },
    images: "../images/zanaatkar.webp",
    aciklama: "Kütürel El Sanatları Workshopuna herkesi bekleriz.",
  },
];

// services/api.js
export const categories = [
  "Tümü",
  "Müzik",
  "Tiyatro",
  "Sinema",
  "Sergi",
  "Dans",
  "Konferans",
  "Festival",
  "Söyleşi",
];

export const mainCategories = [
  "Etkinlikler",
  "Tarihi Yerler",
  "Cafe & Restoranlar",
];
